version: "3.9"

services:
  db:
    image: postgres:16
    container_name: eve-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: eve_main
      POSTGRES_USER: freeman_user
      POSTGRES_PASSWORD: hellotherefreeman
    volumes:
      - /srv/dbs/eve_db_data:/var/lib/postgresql/data
    networks:
      - pgnetwork
    ports:
      - "5432:5432"  # можно оставить только для локальных подключений, необязательно наружу

  backend:
    build: ./backend
    container_name: eve-backend
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: eve_main
      DB_USER: freeman_user
      DB_PASSWORD: hellotherefreeman
    depends_on:
      - db
    networks:
      - pgnetwork
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  pgadmin:
    image: dpage/pgadmin4
    container_name: eve-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: jackeandco@gmail.com
      PGADMIN_DEFAULT_PASSWORD: evebdpassword
    ports:
      - "8080:80"
    networks:
      - pgnetwork
    volumes:
      - /srv/dbs/pgadmin:/var/lib/pgadmin

networks:
  pgnetwork:
    driver: bridge


# Опционально позже можно добавить фронт:
# frontend:
#   build: ./frontend
#   ports:
#     - "3000:3000"
#   depends_on:
#     - backend

