version: "3.9"

services:
  db:
    image: postgres:16
    container_name: eve_local_db
    environment:
      POSTGRES_DB: eve_main
      POSTGRES_USER: freeman_user
      POSTGRES_PASSWORD: hellotherefreeman
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: eve_local_backend_dj
    build:
      context: backend_django
    env_file:
      - backend_django/.env
    environment:
      DJANGO_SETTINGS_MODULE: eve_backend.settings
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: freeman_user
      DB_PASSWORD: hellotherefreeman
      DB_NAME: eve_main
      PORT: 4000

    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./backend_django:/app/backend_django

#  frontend:
#    image: nginx:alpine
#    container_name: eve_local_frontend
#    ports:
#      - "3000:80"  # Добавил порт для доступа
#    volumes:
#      - ./frontend:/usr/share/nginx/html:ro
#    depends_on:
#      - backend

volumes:
  pgdata:
